ANALISADOR_SINTATICO_TABELA = {
    "PROGRAM": {
        "LBRACE": "STATEMENT",
        "SEMICOLON": "STATEMENT",
        "DEF": "FUNCLIST",
        "INT": "STATEMENT",
        "FLOAT": "STATEMENT",
        "STR": "STATEMENT",
        "IF": "STATEMENT",
        "FOR": "STATEMENT",
        "PRINT": "STATEMENT",
        "READ": "STATEMENT",
        "BREAK": "STATEMENT",
        "RETURN": "STATEMENT",
        "IDENT": "STATEMENT",
        "EOF": "",
    },
    "FUNCLIST": {
        "DEF": "FUNCDEF FUNCLIST",
        "EOF": "",
    },
    "FUNCDEF": {
        "DEF": "DEF IDENT LPAREN PARAMLIST RPAREN LBRACE STATELIST RBRACE"
    },
    "PARAMLIST": {
        "RPAREN": "",
        "INT": "TYPE IDENT R13",
        "FLOAT": "TYPE IDENT R13",
        "STR": "TYPE IDENT R13",
    },
    "TYPE": {
        "INT": "INT",
        "STR": "STR",
        "FLOAT": "FLOAT",
    },
    "STATEMENT": {
        "LBRACE": "LBRACE STATELIST RBRACE",
        "SEMICOLON": "SEMICOLON",
        "INT": "VARDECL SEMICOLON",
        "FLOAT": "VARDECL SEMICOLON",
        "STR": "VARDECL SEMICOLON",
        "IF": "IFSTAT ",
        "FOR": "FORSTAT ",
        "PRINT": "PRINTSTAT SEMICOLON",
        "READ": "READSTAT SEMICOLON",
        "BREAK": "BREAK SEMICOLON",
        "RETURN": "RETURN SEMICOLON",
        "IDENT": "ATRIBSTAT SEMICOLON",
    },
    "VARDECL": {
        "INT": "INT IDENT R1",
        "FLOAT": "FLOAT IDENT R1",
        "STR": "STR IDENT R1",
    },
    "ATRIBSTAT": {
        "IDENT": "LVALUE ATRIBUICAO R10"
    },
    "PARAMLISTCALL": {
        "RPAREN": "",
        "IDENT": "IDENT R11",
    },
    "PRINTSTAT": {
        "PRINT": "PRINT EXPRESSION",
    },
    "READSTAT": {
        "READ": "READ LVALUE"
    },
    "IFSTAT": {
        "IF": "IF LPAREN EXPRESSION RPAREN STATEMENT R2"
    },
    "FORSTAT": {
        "FOR": "FOR LPAREN ATRIBSTAT SEMICOLON EXPRESSION SEMICOLON ATRIBSTAT RPAREN STATEMENT"
    },
    "STATELIST": {
        "LBRACE": "STATEMENT R3",
        "RBRACE": "",
        "SEMICOLON": "STATEMENT R3",
        "INT": "STATEMENT R3",
        "FLOAT": "STATEMENT R3",
        "STR": "STATEMENT R3",
        "IF": "STATEMENT R3",
        "FOR": "STATEMENT R3",
        "PRINT": "STATEMENT R3",
        "READ": "STATEMENT R3",
        "BREAK": "STATEMENT R3",
        "RETURN": "STATEMENT R3",
        "IDENT": "STATEMENT R3",
    },
    "ALLOCEXPRESSION": {
        "NEW": "NEW TYPE LBRACKET NUMEXPRESSION RBRACKET R4",
    },
    "EXPRESSION": {
        "LPAREN": "NUMEXPRESSION R5",
        "PLUS": "NUMEXPRESSION R5",
        "MINUS": "NUMEXPRESSION R5",
        "NULL": "NUMEXPRESSION R5",
        "STRING_CONSTANT": "NUMEXPRESSION R5",
        "FLOAT_CONSTANT": "NUMEXPRESSION R5",
        "INT_CONSTANT": "NUMEXPRESSION R5",
        "IDENT": "NUMEXPRESSION R5",
    },
    "NUMEXPRESSION": {
        "LPAREN": "TERM R6",
        "PLUS": "TERM R6",
        "MINUS": "TERM R6",
        "NULL": "TERM R6",
        "STRING_CONSTANT": "TERM R6",
        "FLOAT_CONSTANT": "TERM R6",
        "INT_CONSTANT": "TERM R6",
        "IDENT": "TERM R6",
    },
    "TERM": {
        "LPAREN": "UNARYEXPR R7",
        "PLUS": "UNARYEXPR R7",
        "MINUS": "UNARYEXPR R7",
        "NULL": "UNARYEXPR R7",
        "STRING_CONSTANT": "UNARYEXPR R7",
        "FLOAT_CONSTANT": "UNARYEXPR R7",
        "INT_CONSTANT": "UNARYEXPR R7",
        "IDENT": "UNARYEXPR R7",
    },
    "UNARYEXPR": {
        "LPAREN": "R8 FACTOR",
        "PLUS": "R8 FACTOR",
        "MINUS": "R8 FACTOR",
        "NULL": "R8 FACTOR",
        "STRING_CONSTANT": "R8 FACTOR",
        "FLOAT_CONSTANT": "R8 FACTOR",
        "INT_CONSTANT": "R8 FACTOR",
        "IDENT": "R8 FACTOR",
    },
    "FACTOR": {
        "LPAREN": "LPAREN NUMEXPRESSION RPAREN",
        "NULL": "NULL",
        "STRING_CONSTANT": "STRING_CONSTANT",
        "FLOAT_CONSTANT": "FLOAT_CONSTANT",
        "INT_CONSTANT": "INT_CONSTANT",
        "IDENT": "LVALUE",
    },
    "LVALUE": {
        "IDENT": "IDENT R9",
    },
    "R1": {
        "LBRACKET": "LBRACKET INT_CONSTANT RBRACKET R1",
        "SEMICOLON": "",
        "ATRIBUICAO": "",
    },
    "R2": {
        "LPAREN": "",
        "RPAREN": "",
        "LBRACE": "",
        "RBRACE": "",
        "SEMICOLON": "",
        "INT": "",
        "FLOAT": "",
        "STR": "",
        "IF": "",
        "ELSE": "ELSE STATEMENT",
        "FOR": "",
        "PRINT": "",
        "READ": "",
        "BREAK": "",
        "RETURN": "",
        "IDENT": "",
        "EOF": "",
    },
    "R3": {
        "LPAREN": "",
        "RPAREN": "",
        "LBRACE": "STATELIST",
        "RBRACE": "",
        "SEMICOLON": "STATELIST",
        "INT": "STATELIST",
        "FLOAT": "STATELIST",
        "STR": "STATELIST",
        "IF": "STATELIST",
        "FOR": "STATELIST",
        "PRINT": "STATELIST",
        "READ": "STATELIST",
        "BREAK": "STATELIST",
        "RETURN": "STATELIST",
        "IDENT": "STATELIST",
        "EOF": "",
    },
    "R4": {
        "LBRACKET": "LBRACKET NUMEXPRESSION RBRACKET R4",
        "RPAREN": "",
        "SEMICOLON": "",
    },
    "R5": {
        "RPAREN": "",
        "SEMICOLON": "",
        "MAIOROUIGUAL": "OPERATOR NUMEXPRESSION",
        "MENOROUIGUAL": "OPERATOR NUMEXPRESSION",
        "MENOR": "OPERATOR NUMEXPRESSION",
        "MAIOR": "OPERATOR NUMEXPRESSION",
        "IGUAL": "OPERATOR NUMEXPRESSION",
        "DIFERENTE": "OPERATOR NUMEXPRESSION",
    },
    "R6": {
        "RBRACKET": "",
        "RPAREN": "",
        "MAIOROUIGUAL": "",
        "MENOROUIGUAL": "",
        "MENOR": "",
        "MAIOR": "",
        "IGUAL": "",
        "DIFERENTE": "",
        "PLUS": "SYMBOL1 TERM R6",
        "MINUS": "SYMBOL1 TERM R6",
        "SEMICOLON": "",
    },
    "R7": {
        "RBRACKET": "",
        "RPAREN": "",
        "PLUS": "",
        "MINUS": "",
        "MULTIPLY": "SYMBOL2 UNARYEXPR R7",
        "DIVIDE": "SYMBOL2 UNARYEXPR R7",
        "PERCENT": "SYMBOL2 UNARYEXPR R7",
        "MAIOROUIGUAL": "",
        "MENOROUIGUAL": "",
        "MENOR": "",
        "MAIOR": "",
        "IGUAL": "",
        "DIFERENTE": "",
        "SEMICOLON": "",
    },
    "R8": {
        "LPAREN": "",
        "PLUS": "SYMBOL1",
        "MINUS": "SYMBOL1",
        "STRING_CONSTANT": "",
        "FLOAT_CONSTANT": "",
        "INT_CONSTANT": "",
        "IDENT": "",
        "NULL": "",
    },
    "R9": {
        "LBRACKET": "LBRACKET NUMEXPRESSION RBRACKET R12",
        "RBRACKET": "",
        "LPAREN": "LPAREN PARAMLISTCALL RPAREN",
        "RPAREN": "",
        "SEMICOLON": "",
        "MAIOROUIGUAL": "",
        "MENOROUIGUAL": "",
        "MENOR": "",
        "MAIOR": "",
        "IGUAL": "",
        "DIFERENTE": "",
        "ATRIBUICAO": "",
        "PLUS": "",
        "MINUS": "",
        "MULTIPLY": "",
        "DIVIDE": "",
        "PERCENT": "",
    },
    "R10": {
        "LPAREN": "EXPRESSION",
        "PLUS": "EXPRESSION",
        "MINUS": "EXPRESSION",
        "NULL": "EXPRESSION",
        "NEW": "ALLOCEXPRESSION",
        "STRING_CONSTANT": "EXPRESSION",
        "FLOAT_CONSTANT": "EXPRESSION",
        "INT_CONSTANT": "EXPRESSION",
        "IDENT": "EXPRESSION",
    },
    "R11": {
        "RPAREN": "",
        "COMMA": "COMMA PARAMLISTCALL",
    },
    "R12": {
        "LBRACKET": "LBRACKET NUMEXPRESSION RBRACKET R12",
        "RPAREN": "",
        "SEMICOLON": "",
        "MAIOROUIGUAL": "",
        "MENOROUIGUAL": "",
        "MENOR": "",
        "MAIOR": "",
        "IGUAL": "",
        "DIFERENTE": "",
        "ATRIBUICAO": "",
        "PLUS": "",
        "MINUS": "",
        "MULTIPLY": "",
        "DIVIDE": "",
        "PERCENT": "",
    },
    "R13": {
        "RPAREN": "",
        "COMMA": "COMMA PARAMLIST",
    },
    "SYMBOL1": {
        "PLUS": "PLUS",
        "MINUS": "MINUS",
    },
    "SYMBOL2": {
        "MULTIPLY": "MULTIPLY",
        "DIVIDE": "DIVIDE",
        "PERCENT": "PERCENT",
    },
    "OPERATOR": {
        "MAIOROUIGUAL": "MAIOROUIGUAL",
        "MENOROUIGUAL": "MENOROUIGUAL",
        "MENOR": "MENOR",
        "MAIOR": "MAIOR",
        "IGUAL": "IGUAL",
        "DIFERENTE": "DIFERENTE",
    },
}
